context:
  version: 4.0.3
  sha256: 325b5c806167c13b40b1ffeadfe0248197c00eccc4cf123ec1e28d2d2fd216d9

package:
  name: openssl
  version: ${{ version }}

source:
  url: https://github.com/openssl/openssl/releases/download/openssl-${{ version }}/openssl-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  skip:
    - not osx
    - not x86_64
    - build_platform != target_platform

requirements:
  build:
    - ${{ compiler("c") }}
    - perl >=5.10.0
    - ${{ stdlib("c") }}
  run:
    - ca-certificates
  run_exports:
    - ${{ pin_subpackage("openssl") }}

about:
  documentation: https://docs.openssl.org/master/
  homepage: https://openssl-library.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  repository: https://github.com/openssl/openssl
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
