name: libzlib

on:
  push:
    branches:
      - build-all
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: Build package
    permissions:
      id-token: write
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v7
      - uses: prefix-dev/rattler-build-action@v0
        with:
          rattler-build-version: v0.75.0
          recipe-path: libzlib/recipe.yaml
          upload-artifact: "false"
          build-args: >-
            --no-include-recipe
            --package-format 'conda:22'
            --variant-config variants/ci.yaml
      - run: rattler-build upload prefix -c hingebase/catalina-backports output/osx-64/libzlib-*.conda
